recipe_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path("", views.start),
    path("index/", views.index, name="index"),
    path("", include("django.contrib.auth.urls")),
    path("register/", views.Register.as_view(), name="register"),
    path("register_ok/", views.register_ok, name="register_ok"),
    path("profile/", views.profile, name="profile"),
    path("recipes/add/", views.recipe_add, name="recipe_add"),
    path("recipes/edit/<int:recipe_id>", views.recipe_edit, name="recipe_edit"),
    path("recipes/del/", views.recipe_del, name="recipe_del"),
    path("recipes/", views.recipes, name="recipes"),
    path("recipe_view/<int:recipe_id>", views.recipe_view, name="recipe_view"),

]

recipe_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('recipe_app.urls')),
    # path('api/', include('recipe_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from . import models


class UserCreateForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = models.User
        fields = UserCreationForm.Meta.fields + ("email",)


class RecipeAdd(forms.Form):
    """
    Добавление рецепта.
    """
    categories_data = models.Category.objects.all()

    title = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control', }))
    description = forms.CharField(required=False,
                                  widget=forms.Textarea(attrs={'rows': 2, 'class': 'form-control', }))
    ingredients = forms.CharField(required=True,
                                  widget=forms.Textarea(attrs={'rows': 5, 'class': 'form-control', }))
    steps = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows': 5, 'class': 'form-control', }))
    time_cook = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control', }))
    categories = forms.ModelMultipleChoiceField(queryset=categories_data, required=True, to_field_name="id",
                                                widget=forms.CheckboxSelectMultiple())
    photo = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}, ))


class RecipeEdit(forms.ModelForm):
    id = forms.IntegerField(widget=forms.HiddenInput())
    categories_data = models.Category.objects.all()

    title = forms.CharField(max_length=150, required=True, widget=forms.TextInput(attrs={'class': 'form-control', }))
    description = forms.CharField(required=False,
                                  widget=forms.Textarea(attrs={'rows': 2, 'class': 'form-control', }))
    ingredients = forms.CharField(required=True,
                                  widget=forms.Textarea(attrs={'rows': 5, 'class': 'form-control', }))
    steps = forms.CharField(required=True, widget=forms.Textarea(attrs={'rows': 5, 'class': 'form-control', }))
    time_cook = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control', }))
    categories = forms.ModelMultipleChoiceField(queryset=categories_data, required=True, to_field_name="id",
                                                widget=forms.CheckboxSelectMultiple())
    photo = forms.ImageField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}, ))

    class Meta:
        model = models.Recipe
        fields = ('title', 'description', 'ingredients', 'steps', 'time_cook', 'categories', 'photo',)
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', }),
            'description': forms.Textarea(attrs={'rows': 2, 'class': 'form-control', }),
            'ingredients': forms.Textarea(attrs={'rows': 5, 'class': 'form-control', }),
            'steps': forms.Textarea(attrs={'rows': 5, 'class': 'form-control', }),
            'time_cook': forms.NumberInput(attrs={'class': 'form-control', }),
            'categories': forms.CheckboxSelectMultiple(attrs={'class': 'form-check-input'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}, )
        }


class RecipeDel(forms.Form):
    recipe_id = forms.IntegerField(widget=forms.HiddenInput())

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <title>Каталог рецептов</title>
</head>
<body>

<div class="container-lg">

    <section class="fixed-top">
        <nav class="navbar navbar-expand-lg navbar-light bg-light container-lg">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-cake" viewBox="0 0 16 16">
                        <path d="m7.994.013-.595.79a.747.747 0 0 0 .101 1.01V4H5a2 2 0 0 0-2 2v3H2a2 2 0 0 0-2 2v4a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-4a2 2 0 0 0-2-2h-1V6a2 2 0 0 0-2-2H8.5V1.806A.747.747 0 0 0 8.592.802l-.598-.79ZM4 6a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v.414a.911.911 0 0 1-.646-.268 1.914 1.914 0 0 0-2.708 0 .914.914 0 0 1-1.292 0 1.914 1.914 0 0 0-2.708 0A.911.911 0 0 1 4 6.414V6Zm0 1.414c.49 0 .98-.187 1.354-.56a.914.914 0 0 1 1.292 0c.748.747 1.96.747 2.708 0a.914.914 0 0 1 1.292 0c.374.373.864.56 1.354.56V9H4V7.414ZM1 11a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.793l-.354.354a.914.914 0 0 1-1.293 0 1.914 1.914 0 0 0-2.707 0 .914.914 0 0 1-1.292 0 1.914 1.914 0 0 0-2.708 0 .914.914 0 0 1-1.292 0 1.914 1.914 0 0 0-2.708 0 .914.914 0 0 1-1.292 0L1 11.793V11Zm11.646 1.854a1.915 1.915 0 0 0 2.354.279V15H1v-1.867c.737.452 1.715.36 2.354-.28a.914.914 0 0 1 1.292 0c.748.748 1.96.748 2.708 0a.914.914 0 0 1 1.292 0c.748.748 1.96.748 2.707 0a.914.914 0 0 1 1.293 0Z"/>
                    </svg>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Главная</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'recipes' %}">Мои рецепты</a>
                            </li>
                        {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                        <span class="navbar-text text-sm-end me-3">
                            <a class="btn btn-light" href="{% url 'profile' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                 class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0z"/>
                            <path fill-rule="evenodd"
                                  d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1z"/>
                            </svg>
                            {{ user.username }}
                            </a>
                        </span>
                        <span class="navbar-text">
                        <a class="btn btn-danger text-white" href="{% url 'logout' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                                 class="bi bi-box-arrow-right" viewBox="0 0 16 16">
                              <path fill-rule="evenodd"
                                    d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                              <path fill-rule="evenodd"
                                    d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                            </svg>
                                Выход
                        </a>
                        </span>
                    {% else %}
                        <span class="navbar-text">
                        <a class="btn btn-primary text-white" href="{% url 'login' %}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor"
                                 class="bi bi-person-add" viewBox="0 0 16 16">
                                <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm.5-5v1h1a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1h-1a.5.5 0 0 1 0-1h1v-1a.5.5 0 0 1 1 0Zm-2-6a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/>
                                <path d="M8.256 14a4.474 4.474 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10c.26 0 .507.009.74.025.226-.341.496-.65.804-.918C9.077 9.038 8.564 9 8 9c-5 0-6 3-6 4s1 1 1 1h5.256Z"/>
                            </svg>
                            Вход
                        </a>
                        </span>
                    {% endif %}
                </div>
            </div>
        </nav>
    </section>

    <section style="padding: 75px 0 100px; width: 96%">
        {% block content %}

        {% endblock %}
    </section>


    <footer class="fixed-bottom bg-light container-lg">
        <div class="row">
            <div class="col m-4">
                <h6>Книга рецептов</h6>
                <p><a href="https://gb.ru">GeekBrains</a> - итоговый тест, &copy; 2024. Мамедова С.</p>
            </div>
        </div>
    </footer>
</div>
<script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="h1 text-center">Книга рецептов</h1>
    <hr class="mb-3">

    <div class="row row-cols-1 row-cols-md-3 g-4 pb-5">
        {% for recipe in recipes %}
            <div class="col">
                <div class="card h-100">
                    <img src="{{ recipe.photo.url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ recipe.title }}</h5>
                        <p class="card-text">{{ recipe.description | truncatechars:150 }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">
                            <a class="link-secondary" href="{% url 'recipe_view' recipe_id=recipe.id %}">Нажмите для просмотра</a>
                        </small>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/pagination.html
<nav class="float-sm-end float-start">
    <ul class="pagination">
        {% if page.has_previous %}
            <li class="page-item ">
                <a class="page-link" href="?page={{ page.previous_page_number }}" aria-label="Предыдущая">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Предыдущая">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}
        <li class="page-item page-link">{{ page.number }}</li>
        {% if page.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page.next_page_number }}" aria-label="Следующая">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" aria-label="Следующая">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}
    </ul>
</nav>

templates/profile.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="h1 text-center">Профиль пользователя</h1>

    <div class="col-lg-4 col-md-6 m-auto">
        <div class="mb-2">
            <label class="form-label">Логин</label>
            <label class="form-label fw-bold">{{ user.username }}</label>
        </div>

        <div class="mb-2">
            <label class="form-label">E-Mail</label>
            <label class="form-label fw-bold">{{ user.email }}</label>
        </div>
    </div>

{% endblock %}

templates/recipe_add.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">Новый рецепт</h1>
    <div class="col-lg-6 col-md-8 mb-4 ms-auto me-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}


            <div class="mb-2">
                <label class="form-label" for="id_title">Название</label>
                {{ form.title }}
            </div>

            <div class="mb-2">
                <label class="form-label" for="id_description">Описание</label>
                {{ form.description }}
            </div>

            <div class="mb-2">
                <label class="form-label">Ингредиенты</label>
                {{ form.ingredients }}
            </div>

            <div class="mb-2">
                <label class="form-label">Приготовление</label>
                {{ form.steps }}
            </div>

            <div class="mb-2">
                <label class="form-label">Время приготовления</label>
                {{ form.time_cook }}
            </div>

            <div class="mb-2">
                <label class="form-label">Категории</label>
                {{ form.categories }}
            </div>

            <div class="mb-2">
                <label class="form-label">Изображение</label>
                {{ form.photo }}
            </div>

            <button class="btn btn-success" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-floppy2-fill" viewBox="0 0 16 16">
                    <path d="M12 2h-2v3h2V2Z"/>
                    <path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v13A1.5 1.5 0 0 0 1.5 16h13a1.5 1.5 0 0 0 1.5-1.5V2.914a1.5 1.5 0 0 0-.44-1.06L14.147.439A1.5 1.5 0 0 0 13.086 0H1.5ZM4 6a1 1 0 0 1-1-1V1h10v4a1 1 0 0 1-1 1H4ZM3 9h10a1 1 0 0 1 1 1v5H2v-5a1 1 0 0 1 1-1Z"/>
                </svg>
                Сохранить
            </button>
        </form>
    </div>

{% endblock %}

templates/recipe_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="text-center">Изменить рецепт</h1>
    <div class="col-lg-6 col-md-8 mb-4 ms-auto me-auto">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.id }}

            <div class="mb-2">
                <label class="form-label" for="id_title">Название</label>
                {{ form.title }}
            </div>

            <div class="mb-2">
                <label class="form-label" for="id_description">Описание</label>
                {{ form.description }}
            </div>

            <div class="mb-2">
                <label class="form-label" for="id_ingredients">Ингредиенты</label>
                {{ form.ingredients }}
            </div>

            <div class="mb-2">
                <label class="form-label" for="id_steps">Приготовление</label>
                {{ form.steps }}
            </div>

            <div class="mb-2">
                <label class="form-label" for="id_time_cook">Время приготовления</label>
                {{ form.time_cook }}
            </div>

            <div class="mb-2">

<label class="form-label" for="{{ form.categories.id_for_label }}">Категории</label>
<ul>
  {% for category in form.categories %}
    <li>
      {{ category }}
      <label for="{{ category.id_for_label }}">{{ category.choice_label }}</label>
    </li>
  {% endfor %}
</ul>

<!--<label class="form-label" for="id_categories">Категории</label>-->
<!--<ul>-->
<!--  {% for category in form.categories %}-->
<!--    <li>-->
<!--      {{ category }}-->
<!--      <label for="id_categories_{{ forloop.index0 }}">{{ category.choice_label }}</label>-->
<!--    </li>-->
<!--  {% endfor %}-->
<!--</ul>-->




            </div>

            <div class="mb-2">
                <label class="form-label" for="id_photo">Изображение</label>
                {{ form.photo }}
            </div>

            <button class="btn btn-success" type="submit">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-floppy2-fill" viewBox="0 0 16 16">
                    <path d="M12 2h-2v3h2V2Z"/>
                    <path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v13A1.5 1.5 0 0 0 1.5 16h13a1.5 1.5 0 0 0 1.5-1.5V2.914a1.5 1.5 0 0 0-.44-1.06L14.147.439A1.5 1.5 0 0 0 13.086 0H1.5ZM4 6a1 1 0 0 1-1-1V1h10v4a1 1 0 0 1-1 1H4ZM3 9h10a1 1 0 0 1 1 1v5H2v-5a1 1 0 0 1 1-1Z"/>
                </svg>
                Сохранить
            </button>
        </form>
    </div>

{% endblock %}

templates/recipe_view.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ recipe.title }}</h1>

    <div class="card mb-5" style="max-width: 100%;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ recipe.photo.url }}" class="card-img-top" alt="..." width="400px">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="Описание">Описание</h5>
                    <p class="card-text">{{ recipe.description }}</p>
                    <h5 class="Описание">Ингредиенты</h5>
                    <p class="card-text" style="white-space: pre-wrap;">{{ recipe.ingredients }}</p>
                    <h5 class="Описание">Приготовление</h5>
                    <p class="card-text" style="white-space: pre-wrap;">{{ recipe.steps }}</p>
                    <p class="card-text">Время приготовления: <span
                            class="fw-bold">{{ recipe.time_cook }} </span>мин.
                    </p>
                    <p class="card-text "><small><strong>Категории</strong>:
                        {% for category in recipe.categories.all %}
                            {{ category }},
                        {% endfor %}
                    </small>
                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/recipes.html
{% extends 'base.html' %}

{% block content %}

    {#    <!-- Button trigger modal -->#}
    {#    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#deleteAlert">#}
    {#        Launch demo modal#}
    {#    </button>#}

<!--     Modal-->
    <div class="modal fade" id="deleteAlert" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Удалить рецепт</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <form action="{% url 'recipe_del' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="recipe_id" id="recipe_id" value=0>
                        <button type="submit" class="btn btn-danger" data-bs-dismiss="modal">Удалить</button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </div>

    <h1 class="text-center">Список моих рецептов</h1>
    <hr>

    <div class="row">
        <div class="col-sm-6 mb-2">
            <a class="btn btn-primary" href="{% url 'recipe_add' %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-plus-circle"
                     viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
                </svg>
                Новый
            </a>
        </div>
        <div class="col-sm-6 mb-2">
            {% include 'pagination.html' with page=recipes %}
        </div>

        <section>
            <table class="table table-hover table-sm table-bordered table-striped">
                <thead class="bg-gradient bg-dark text-light">
                <tr>
                    <th>Название</th>
                    <th>Описание</th>
                    <th>Время приготовления</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for recipe in recipes %}
                    <tr>

                        <td>
                            <a class="link-secondary" href="{% url 'recipe_view' recipe_id=recipe.id %}" title="Подробно">
                                {{ recipe.title }}
                            </a>
                        </td>
                        <td>
                            {{ recipe.description | truncatechars:100 }}
                        </td>
                        <td>{{ recipe.time_cook }}</td>
                        <td>
                            <a class="btn btn-sm btn-warning" href="{% url 'recipe_edit' recipe_id=recipe.id %}" title="Изменить">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd"
                                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                </svg>
                            </a>
                        </td>
                        <td>
                            <button name="btnDelete" type="button" class="btn btn-sm btn-danger" title="Удалить"
                                    data-recipeId="{{ recipe.id }}" data-bs-toggle="modal" data-bs-target="#deleteAlert"
                                    data-recipeTitle="{{ recipe.title }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-trash" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5Zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6Z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1ZM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118ZM2.5 3h11V2h-11v1Z"/>
                                </svg>
                            </button>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </section>
    </div>


    <script>
        "use strict";
        document.querySelector('#deleteAlert').addEventListener('show.bs.modal', function (event) {
            const button = event.relatedTarget;
            const id = button.dataset.recipeid;
            const title = button.dataset.recipetitle;
            const modal = this;
            modal.querySelector('.modal-body').textContent = 'Удалить ' + '"' + title + '" из списка рецептов?';
            modal.querySelector('#recipe_id').value = id
        })
    </script>

{% endblock %}